version: "3.9"  # Use the latest stable version (as of February 14, 2024)

services:
  frontend:
    build:
      context: ./vuejsfrontendwithdocker
      dockerfile: Dockerfile
    image: frontend:latest
    ports:
      - "8080:8080"
    depends_on:
      - backend  # Wait for the backend service to be ready

  backend:
    build:
      context: ./pythonbackendwithdocker
      dockerfile: Dockerfile
    image: backend:latest
    ports:
      - "5000:5000"  # Map container port 5000 to 5000 on the host