import { createApp } from "vue";
import App from "./App.vue";
import PrimeVue from "primevue/config";
import "primeicons/primeicons.css";
import "primevue/resources/themes/lara-light-indigo/theme.css";
import "primeflex/primeflex.css";

import Button from "primevue/button";
import TabMenu from "primevue/tabmenu";
import Card from "primevue/card";
import RadioButton from "primevue/radiobutton";
import InputNumber from "primevue/inputnumber";
import InputText from "primevue/inputtext";
import DataTable from 'primevue/datatable';
import Column from 'primevue/column';
import ColumnGroup from 'primevue/columngroup';
import Row from 'primevue/row';
import Toast from 'primevue/toast';
import ToastService from "primevue/toastservice";
import Image from 'primevue/image';
import Dialog from "primevue/dialog";
import Divider from "primevue/divider";
import Dropdown from "primevue/dropdown";
import ColorPicker from "primevue/colorpicker";
import CascadeSelect from 'primevue/cascadeselect';
import ToggleButton from "primevue/togglebutton";


const app = createApp(App);
app.use(PrimeVue);
app.use(ToastService);
app.component("Button", Button);
app.component("TabMenu", TabMenu);
app.component("Card", Card);
app.component("RadioButton", RadioButton);
app.component("InputNumber", InputNumber);
app.component("DataTable", DataTable);
app.component("Column", Column);
app.component("ColumnGroup", ColumnGroup);
app.component("Row", Row);
app.component("InputText", InputText);
app.component("Toast", Toast);
app.component("Image", Image);
app.component("Dialog", Dialog);
app.component("Divider", Divider);
app.component("Dropdown", Dropdown);
app.component("ColorPicker", ColorPicker);
app.component("CascadeSelect", CascadeSelect);
app.component("ToggleButton", ToggleButton);
app.mount("#app");